version: "3.8"
services:
  elasticsearch-1:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch-1
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch-1-data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      node.name: es-node01
      discovery.seed_hosts: elasticsearch-1,elasticsearch-2,elasticsearch-3
      cluster.initial_master_nodes: es-node01,es-node02,es-node03
      # bootstrap.memory_lock: 'true'
      discovery.zen.minimum_master_nodes: 2
    networks:
      - elk
    ulimits:
      memlock:
        soft: -1
        hard: -1

  elasticsearch-2:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch-2
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch-2-data
        target: /usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      node.name: es-node02
      discovery.seed_hosts: elasticsearch-1,elasticsearch-2,elasticsearch-3
      cluster.initial_master_nodes: es-node01,es-node02,es-node03
      # bootstrap.memory_lock: 'true'
      discovery.zen.minimum_master_nodes: 2
    networks:
      - elk
    ulimits:
      memlock:
        soft: -1
        hard: -1

  elasticsearch-3:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch-3
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch-3-data
        target: /usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      node.name: es-node03
      discovery.seed_hosts: elasticsearch-1,elasticsearch-2,elasticsearch-3
      cluster.initial_master_nodes: es-node01,es-node02,es-node03
      # bootstrap.memory_lock: 'true'
      discovery.zen.minimum_master_nodes: 2
    networks:
      - elk
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch-1:9200","http://elasticsearch-2:9200"]
    networks:
      - elk
    depends_on:
      - elasticsearch-1
      - elasticsearch-2
      - elasticsearch-3

volumes:
  elasticsearch-1-data:
  elasticsearch-2-data:
  elasticsearch-3-data:

networks:
  elk:
    driver: bridge
